--- 
document: 
  description: "La guida al linguaggio della Pubblica Amministrazione è uno strumento per aiutarti a creare e gestire i contenuti di siti o altri servizi digitali pubblici. La guida al linguaggio è parte del kit di Designers Italia dedicato alla progettazione, gestione e produzione di contenuti nei siti della Pubblica Amministrazione."
  name: "Guida al linguaggio della Pubblica Amministrazione"
  tags: 
    - linguaggio
    - design
